USE [FactoryInventory]
GO

/****** Object:  Index [Dates]    Script Date: 09-04-2020 16:39:19 ******/
CREATE NONCLUSTERED INDEX [temp] ON [dbo].[temp]
(
	[C1] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


