USE [master]
GO
/****** Object:  Database [Main]    Script Date: 02-01-2021 12:40:30 ******/
CREATE DATABASE [Main]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Main', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Main.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Main_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Main_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Main] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Main].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Main] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Main] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Main] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Main] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Main] SET ARITHABORT OFF 
GO
ALTER DATABASE [Main] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Main] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Main] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Main] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Main] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Main] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Main] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Main] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Main] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Main] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Main] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Main] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Main] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Main] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Main] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Main] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Main] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Main] SET RECOVERY FULL 
GO
ALTER DATABASE [Main] SET  MULTI_USER 
GO
ALTER DATABASE [Main] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Main] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Main] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Main] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Main] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Main', N'ON'
GO
ALTER DATABASE [Main] SET QUERY_STORE = OFF
GO
USE [Main]
GO
/****** Object:  Table [dbo].[Firms_List]    Script Date: 02-01-2021 12:40:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Firms_List](
	[Firm_ID] [int] IDENTITY(1,1) NOT NULL,
	[Firm_Name] [varchar](100) NOT NULL,
	[Active_User] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[Firm_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Main] SET  READ_WRITE 
GO